// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

namespace ScrobbleBot.Domain.Entities
{
    using System.Text.Json.Serialization;

    public partial class WeeklyChart
    {
        [JsonPropertyName("weeklychartlist")]
        public Weeklychartlist Weeklychartlist { get; set; }
    }

    public partial class Weeklychartlist
    {
        [JsonPropertyName("chart")]
        public Chart[] Chart { get; set; }

        [JsonPropertyName("@attr")]
        public Attr Attr { get; set; }
    }

    public partial class Chart
    {
        [JsonPropertyName("#text")]
        public string Text { get; set; }

        [JsonPropertyName("from")]
        public long From { get; set; }

        [JsonPropertyName("to")]
        public long To { get; set; }
    }
}
